services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
        - SECRET_KEY=${SECRET_KEY}
        - DATAFORSEO_LOGIN=${DATAFORSEO_LOGIN}
        - DATAFORSEO_PASSWORD=${DATAFORSEO_PASSWORD}
        - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@db:5432/app}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - USE_MOCK_DATA=${USE_MOCK_DATA:-false}
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DATAFORSEO_LOGIN=${DATAFORSEO_LOGIN}
      - DATAFORSEO_PASSWORD=${DATAFORSEO_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_MOCK_DATA=${USE_MOCK_DATA:-false}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge