services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    environment:
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DATAFORSEO_LOGIN=${DATAFORSEO_LOGIN}
      - DATAFORSEO_PASSWORD=${DATAFORSEO_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_MOCK_DATA=${USE_MOCK_DATA:-false}
      - DATABASE_URL=${DATABASE_URL}
    expose:
      - "8000"
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: mamba-nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
