"""add_google_oauth_tokens_table_and_user_relationship

Revision ID: 12b6d19acc7a
Revises: 4476860c69a0
Create Date: 2025-05-11 16:32:03.296882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql # Uncomment if using specific PG types like JSONB explicitly

# revision identifiers, used by Alembic.
revision: str = '12b6d19acc7a'
down_revision: Union[str, None] = '4476860c69a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_oauth_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('service_name', sa.Enum('SEARCH_CONSOLE', 'GOOGLE_ANALYTICS_4', name='googleservice'), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_oauth_tokens_id'), 'google_oauth_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_google_oauth_tokens_service_name'), 'google_oauth_tokens', ['service_name'], unique=False)
    op.create_index(op.f('ix_google_oauth_tokens_user_email'), 'google_oauth_tokens', ['user_email'], unique=False)
    op.create_index('idx_google_token_user_service', 'google_oauth_tokens', ['user_email', 'service_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_google_token_user_service', table_name='google_oauth_tokens')
    op.drop_index(op.f('ix_google_oauth_tokens_user_email'), table_name='google_oauth_tokens')
    op.drop_index(op.f('ix_google_oauth_tokens_service_name'), table_name='google_oauth_tokens')
    op.drop_index(op.f('ix_google_oauth_tokens_id'), table_name='google_oauth_tokens')
    op.drop_table('google_oauth_tokens')
    # Downgrading the Enum type if it was created by this migration
    sa.Enum(name='googleservice').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
